### ISSUE TITLE
DHVI - Luminex Levey-Jennings Report Improvements - Levey-Jennings data grid improvements dev

### ISSUE THREAD

**Issue by cnathe** [LabKey/commonAssays#573]
[Epic](https://github.com/LabKey/commonAssays/issues/571)
[Spec](https://docs.google.com/document/d/1IJIHAfxJ5wdMCOkrNYcON8aFbiC1za34wuQhCPyh11k/edit)

**Tasks**

- [x] Switch L-J report grid to LabKey data region - 5hr
- [x] Allow for grid view customization - 3hr
- [x] Sync grid filtering with plot display - 3hr
- [x] Handle both the titration and single point control version of the report - 3hr
- [x] Highlight grid Guide Set Start Date column values to be bold if members of guide set - 2hr
- [x] Reapply “Apply Guide Set” button functionality - 3hr
- [x] Reapply “View 4PL Curves” button functionality - 2hr
- [x] Reapply “QC Flags” column functionality - 2hr
- [x] Remove current filter options that are above the plot - 0.5hr
- [x] Update spec - 0.5hr
- [x] Code review - 1hr @labkey-klum 
- [x] Test plan - 1hr
- [x] Manual testing - 2hr @labkey-tchad 
- [x] Selenium test updates - 3hr @cnathe 
- [x] TeamCity review and merge - 1hr
