### ISSUE TITLE
Importing giant assay XSLX file

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/commonAssays#762]
[Issue](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=50138)

### Tasks
- [x] Multi-threaded parsing for XLSX - 3
- [x] Stream rows from ExcelLoader - 2
- [x] Stream rows through assay import - 3
- [x] Stream rows through transform scripts - 3
- [x] Stream rows for post-import - 3
- [x] Test fixes  
- [x] manual test plan - 1
- [x] manual testing - 2 @labkey-matthewb  
- [x] manual testing - 2 @labkey-chrisj  
- [x] Automated test coverage for .xlsx @labkey-chrisj 
  - Update existing tests to use .xlsx files and ensure both .xls and .xlsx variants are covered.
  - [x] New import/export coverage for 'worst-case' xlsx data
- [x] code review - 1 @labkey-matthewb 
- [x] Fix Luminex tests @labkey-jeckels https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_ModuleSuites_LuminexPostgres/3073010?hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildChangesSection=true&expandBuildTestsSection=true
- [x] Fix other tests https://teamcity.labkey.org/buildConfiguration/LabkeyTrunk_DailyPostgres_2/3078043?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true @labkey-jeckels 
- [x] teamcity review and merge - 1

### Risk Assessment
_Identify potential risks and propose mitigation strategies. Each team member should contribute by highlighting any risks they foresee, considering business, user, project management, technical, and quality assurance aspects._

- Parsing changes: deadlocks, unclosed resources (especially in error conditions)
  - Impact: High
  - Likelihood: Medium/Low
  - Mitigation: Unit tests
- Risk: Mangled handling of edge cases (zero-row imports, required field checks, import aliases, etc). Possibility of data loss if columns aren't mapped correctly.
  - Impact: Medium
  - Likelihood: Medium
  - Mitigation: Manual test, review automated coverage and consider bolstering
- Risk: Mangled handling of post-import processing (provenance, plate metadata)
  - Impact: Medium
  - Likelihood: Medium
  - Mitigation: Manual test, review automated coverage and consider bolstering
- Risk: Mangled handling in other assay types
  - Impact: High
  - Likelihood: Low
  - Mitigation: Manual test, review automated coverage and consider bolstering

### Manual Test Plan
- Generally, be on the lookout for lingering threads with a name starting with `Async XLSX parser:`. These shouldn't stick around longer than the import is actively running. You can check via Running Threads in the Admin Console or the debugger.
- Standard assay
  - Import small/large XLSX files with expected structure (happy path)
    - Resolve fields via name, labels, import aliases, and property URIs
  - Verify zero row files give helpful error (consistently with 24.3)
  - Verify required fields get enforced with helpful error
  - Verify provenance is connected correctly (has automated coverage that I broke and then fixed)
  - Verify plate metadata works as before (note: Josh is unfamiliar with this area)
  - Verify transform scripts can transform data (note: currently loads all transformed rows into memory at once)
  - Verify basic import works for TSV/CSV as well (don't need to duplicate full XLSX testing)
  - Verify SaveBatch API works
- Luminex assay, basic use (has automated coverage)
- NAb assay, basic use (has automated coverage)
- Viability assay, basic use (has automated coverage)

**Comment by labkey-chrisj** [comment]
Some results

- [ ] [LuminexExcludableWellsTest.testReplicateGroupExclusion](https://teamcity.labkey.org/viewLog.html?buildId=3066977&tab=buildResultsDiv&buildTypeId=LabkeyTrunk_ModuleSuites_LuminexPostgres#testNameId76175974640761545) is failing on fb_50138_xlsxStreaming; I can't repro locally because the test fails before getting to this point
    - screenshot for this failure shows an empty grid, perhaps worth investigating/possibly the test needs to await data
    -  otherwise Luminex seems to be in good shape 
- [ ] [iterator.ValidatingDataRowIterator](https://teamcity.labkey.org/viewLog.html?buildId=3065807&buildTypeId=LabkeyTrunk_Bvt&fromSakuraUI=true#testNameId-4572816498881863852) fails with explanation that the validatingDataRowIterator should have one public constructor, no runnable methods
- [x] Import of 500k rows x 26 string columns (13M distinct values) imports successfully as async upload or as synchronous
    - this scenario succeeds with 2gb heap, fails due to OutOfMemoryError with 1gb 
- [x] required fields supply helpful warning for empty values
- [x] fields identified by import alias, name, label resolve as expected
- [x] zero row file helpfully warns with error
- [x] import of plate metadata still works
- [x] transform scripts (in plates tests, luminex tests) work as expected
    - happy path only, did not do large/chaos file import 
- [x] basic import works as expected for tsv/csv
- [x] provenance tests run green
- [x] NAb runs green

**Comment by labkey-matthewb** [comment]
I can repro the LuminexExcludableWellsTest.testReplicateGroupExclusion failure locally if it's helpful.  I haven't worked out what is going wrong.
