### ISSUE TITLE
[LabKey CI] Remove MS2 GWT code

### ISSUE THREAD

**Issue by labkey-jeckels** [LabKey/commonAssays#829]
### Tasks 📍
- [x] Convert MS2 pipeline jobs to FileAnalysisJobs
- [x] Enable simple XML job launcher for XTandem
- [x] Get default parameters working 
- [x] Enable simple XML job launcher for other search engines
- [x] Remove GWT code
- [x] Reach out to Novartis for use cases @keith-labkey 
- [x] Delete fraction rollup job 
- [x] Check for need to support WAITING FOR FILES
- [x] Remove unused constructors, etc
- [x] Delete MS2's SearchAction
- [x] Update tests 
- [x] Manual test @labkey-ians 📌 
- [x] Code review @labkey-adam 
- [ ] Docs handoff
- [x] Merge
